

    MODUI_INTERRUPTS_TO_TRACK = {
        ['Bash']                    = true, 
        ['Bear Form']               = true, 
        ['Blackout']                = true, 
        ['Blind']                   = true, 
        ['Blink']                   = true,
        ['Cat Form']                = true, 
        ['Charge Stun']             = true, 
        ['Cheap Shot']              = true, 
        ['Concussion Blow']         = true, 
        ['Counterspell - Silenced'] = true,
        ['Death Coil']              = true, 
        ['Dire Bear Form']          = true, 
        ['Divine Intervention']     = true, 
        ['Divine Protection']       = true, 
        ['Divine Shield']           = true,
        ['Earth Shock']             = true, 
        ['Elemental Mastery']       = true,
        ['Fear']                    = true, 
        ['Feral Charge Effect']     = true, 
        ['Fire Ward']               = true, 
        ['Freezing Trap Effect']    = true, 
        ['Frost Armor']             = true, 
        ['Frost Ward']              = true,
        ['Gouge']                   = true, 
        ['Ghost Wolf']              = true,
        ['Hammer of Justice']       = true,
        ['Ice Armor']               = true, 
        ['Ice Barrier']             = true, 
        ['Ice Block']               = true, 
        ['Impact']                  = true, 
        ['Inferno Effect']          = true, 
        ['Inner Fire']              = true, 
        ['Intercept Stun']          = true, 
        ['Intimidating Shout']      = true,
        ['Intimidation']            = true,
        ['Iron Grenade']            = true,
        ['Kidney Shot']             = true, 
        ['Kick']                    = true, 
        ['Kick - Silenced']         = true,
        ['Lightning Shield']        = true,
        ['Mace Stun Effect']        = true,
        ['Mage Armor']              = true,
        ['Mana Shield']             = true,
        ['Nature\'s Swiftness']     = true,
        ['Polymorph']               = true,
        ['Polymorph: Pig']          = true,
        ['Polymorph: Turtle']       = true,
        ['Pounce']                  = true,
        ['Psychic Scream']          = true,
        ['Pummel']                  = true,
        ['Reckless Charge']         = true, 
        ['Revenge Stun']            = true,
        ['Scatter Shot']            = true, 
        ['Seal of the Crusader']    = true,
        ['Seal of Righteousness']   = true,
        ['Shadow Ward']             = true,
        ['Shield Bash']             = true, 
        ['Shield Bash - Silenced']  = true, 
        ['Silence']                 = true,
        ['Spell Lock']              = true,
        ['Starfire Stun']           = true,
        ['Stun']                    = true,
        ['Thorium Grenade']         = true,
        ['Tidal Charm']             = true, 
        ['Travel Form']             = true,
        ['Wyvern Sting']            = true,
    }



    --